In [1]:
pip install torch

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
import torch

In [4]:
x = torch.empty(2, 3) #
print(x)

tensor([[2.3168e-35, 0.0000e+00, 5.0447e-44],
        [0.0000e+00,        nan, 6.4460e-44]])


In [5]:
x = torch.rand(2,2)
print(x)

tensor([[0.4319, 0.3617],
        [0.6067, 0.8339]])


In [6]:
torch.zeros(2)

tensor([0., 0.])

In [7]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [8]:
print(x.dtype)

torch.float32


In [17]:
x = torch.rand(2,3, dtype = torch.float64)

In [18]:
print(x.size())

torch.Size([2, 3])


In [20]:
x = torch.tensor([2, 4, 5.3], dtype = torch.float32)

In [21]:
y = torch.tensor([2, 4, 5.3], dtype = torch.float32)

In [22]:
x+y

tensor([ 4.0000,  8.0000, 10.6000])