In [1]:
pip install torch

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
import numpy as np 
import torch

In [6]:
x = torch.ones(3,3, requires_grad = True)
print(x)

y = x + 2
print(y)
y += 2
print(y)
y += 2
print(y)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)
tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]], grad_fn=<AddBackward0>)
tensor([[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]], grad_fn=<AddBackward0>)
tensor([[7., 7., 7.],
        [7., 7., 7.],
        [7., 7., 7.]], grad_fn=<AddBackward0>)
