In [2]:
import numpy as np 
import torch
import torch.nn as nn

In [4]:
def softmax(x):
    return np.exp(x)/ np.sum(np.exp(x),  axis = 0)


In [6]:
x = np.array([2.0, 1.0, 0.2])
outputs = softmax(x)
print(outputs)

[0.65223985 0.23994563 0.10781452]


In [8]:
x = torch.tensor([2.0, 1.0, 0.1])
outputs = torch.softmax(x, dim = 0)
print(outputs)

tensor([0.6590, 0.2424, 0.0986])


In [16]:
def cross_entropy(actual, predicted):
    loss = - np.sum(actual * np.log(predicted))
    return loss

In [17]:
Y = np.array([1, 0, 0])
y_pred_good = np.array([0.7, 0.2, 0.1])
y_pred_bad = np.array([0.1, 0.3, 0.6])

In [20]:
l_good = cross_entropy(Y, y_pred_good)
l_bad = cross_entropy(Y, y_pred_bad)


In [21]:
print(f'Loss 1 numpy: {l_good:.4f}')
print(f'Loss 2 numpy: {l_bad:.4f}')

Loss 1 numpy: 0.3567
Loss 2 numpy: 2.3026


In [25]:
loss = nn.CrossEntropyLoss()

Y = torch.tensor([0])
# n_samples X n_class = 1 X 3
y_pred_good = torch.tensor([[2.0, 1.0, 0.1]]) #raw value
y_pred_bad = torch.tensor([[.5, 2.0, 0.3]]) #raw value

l1 = loss(y_pred_good, Y)
l2 = loss(y_pred_bad, Y)

print(l1.item())
print(l2.item())

0.4170299470424652
1.840616226196289


In [27]:
_, parediction_good = torch.max(y_pred_good, 1)
_, parediction_bad = torch.max(y_pred_bad, 1)


print(parediction_good)
print(parediction_bad)

tensor([0])
tensor([1])


In [28]:
class NeuralNet1(nn.Module):
    def __init__(self, input_size, hidden_size):
        super(NeuralNet1, self).__init__()

        self.linear1 = nn.Linear(input_size, hidden_size)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(hidden_size, 1)

    def forward(self, x):
        out = self.linear1(x)
        out = self.relu(out)
        out = self.linear2(out)

        y_pred = torch.sigmoid(out)

        return y_pred

In [31]:
model = NeuralNet1(input_size = 28 * 28, hidden_size = 5)
criterion = nn.BCELoss()